#!/bin/bash
HIGHLIGHT="#ffffff"
clock() {
	TIME=$(date "+%l:%M")
	DATE=$(date "+%a %D")
	echo -n " %{F$HIGHLIGHT}$(printf '%b' "\ue016")%{F-}$TIME  %{F$HIGHLIGHT}$(printf '%b' "\ue26a")%{F-} $DATE "
}
volume() {
	VOL=$(amixer get Master | grep % | sed -n 1p | awk -F '[' '{print $2}' | awk -F ']' '{print $1}')
	if [ $VOL = '0%' ]; then
		echo -n " %{F$HIGHLIGHT}$(printf '%b' "\ue04f")%{F-} Mute "
	else
		echo -n " %{F$HIGHLIGHT}$(printf '%b' "\ue050")%{F-} $VOL "
	fi
}

internalip(){
	internal=$(hostname -i)
	external=$(cat /home/user/.config/lemonbar/ipinfo)
	echo -n -e "\uf012 $internal- $external"
}
#music() {
#	SONG=$(mpc current)
#	if [ -n $SONG ]; then
#		echo -n ""
#	else
#		echo -n "%{F$HIGHLIGHT}$(printf '%b' "\ue05c")%{F-} $SONG"
#	fi
#}
windowtitle(){
	# Grabs focused window's title
	# The echo "" at the end displays when no windows are focused.
	TITLE=$(xdotool getactivewindow getwindowname 2>/dev/null | sed -n 1p || echo "")
	TITLECUT=$(xdotool getactivewindow getwindowname 2>/dev/null | sed -n 1p | sed 's/\///g;s/-//g;s/ /\\/g' | cut -c 1-6 || echo "")

	if [ $TITLECUT = "user@" ]; then
		echo "$(printf '%b' "\ue1d9") $(echo "$TITLE" | cut -c 15-50)"
	else
		echo "$TITLE" | cut -c 1-50
	fi
}

while true; do
	echo -e "$(clock)$(internalip)"
	sleep .1;
done | lemonbar -p -d -B#c0262626 -F#A0A0A0 -g 1892x20+1930+10 -r 3 -R#FF993d00 -f "Source Code Pro-11" -f "fontawesome-11"

# %{r}%{B#c0303048}%{B-}
