#!/bin/bash
while true; do
	echo -e "%{c}$(hostname -i)\ue91b $(cat /home/user/.config/lemonbar/ipinfo)"
	sleep 1;
done | lemonbar -p -d -B#c0262626 -F#A0A0A0 -a 1 -g 255x20+2139+10 -r 3 -R#FF993d00 -f "Source Code Pro-9" -f "fontawesome-12" -f "icomoon:size=11"
