#!/bin/bash
while true; do
	echo -e "%{c}$(date "+%l:%M %p") \ue94e $(date "+%a %D")"
	sleep 60;
done | lemonbar -p -d -B#c0262626 -F#A0A0A0 -a 1 -g 195x20+1932+10 -r 3 -R#FF993d00 -f "Source Code Pro-9" -f "Icomoon-11"
